logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


twitter:
  consumerKey: 2MGnrxB4gmQwrcaGpoHcNE4zG
  consumerSecret: 5EijMBN13Yd4d9oml6SLpI7Fj8oD7Knn9fAa23q7xYhz6RJuBx
  accessToken: 132458550-80h35yjXHrIg2btXI7yozwVEhdRTgKc0Yv1dH7Us
  accessTokenSecret: 8AyB3m4NUx98X7FQyzfWzXHRSSsdlCtWf8FkEQ9K22q1S

what3words:
  url: https://api.what3words.com/v2/autosuggest
  apiKey: L7NRCXAQ

googleMap:
  url: https://maps.googleapis.com/maps/api/staticmap
  apiKey: AIzaSyBHVWDKNHzV2vdcuMNLm2Nlve2qphLAtrM
  zoom: 14
  size: 640x480

wordnik:
  url: http://api.wordnik.com:80/v4/words.json/randomWords
  apiKey: 6fdd5670d51652dae150406f02c0df9eb67e537b6bf1f4683